name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing secrets 🔒
        shell: bash
        run: echo ${{ secrets.TEST_SECRET }} > $HOME/.testsecret
      - name: print secret
        run: cat $HOME/.testsecret | grep lakshya
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
